name: CI

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --nologo --no-restore

      - name: Test
        run: dotnet test -r artifacts/TestResults --logger "html"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: AssemblyLine.TestResults
          path: |
            artifacts/TestResults/TestResult*.html